export const site = {
  name: 'Diamantaire Saint-Étienne',
  legalName: 'Diamantaire Saint-Étienne — Expertise & Rachat',
  domain: 'diamantaire-saint-etienne.fr',
  url: 'https://diamantaire-saint-etienne.fr',
  tagline: 'Rachat de diamants et bijoux signés à Saint-Étienne',
  description:
    "Diamantaire à Saint-Étienne : notre réseau de négociants vous reçoit dans un bureau d’échange privé pour le rachat de diamants, bijoux signés (Cartier, Van Cleef & Arpels, Bulgari, Chopard, Tiffany), or et montres de luxe. Expertise gratuite, paiement immédiat, confidentialité absolue — Saint-Étienne, Loire & Auvergne-Rhône-Alpes.",
  phone: '+33 1 42 77 75 55',
  phoneDisplay: '01 42 77 75 55',
  email: 'contact@obagem.fr',
  address: {
    street: 'Bureau d’échange — sur rendez-vous, Saint-Étienne',
    postalCode: '42000',
    city: 'Saint-Étienne',
    region: 'Auvergne-Rhône-Alpes',
    country: 'FR',
    geo: { lat: 45.4397, lng: 4.3872 },
  },
  hours: [
    { day: 'Lundi', open: '10:00', close: '19:00' },
    { day: 'Mardi', open: '10:00', close: '19:00' },
    { day: 'Mercredi', open: '10:00', close: '19:00' },
    { day: 'Jeudi', open: '10:00', close: '19:00' },
    { day: 'Vendredi', open: '10:00', close: '19:00' },
    { day: 'Samedi', open: '10:00', close: '18:00' },
    { day: 'Dimanche', open: 'Fermé', close: '' },
  ],
  social: {
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
  },
  brands: [
    'Cartier',
    'Van Cleef & Arpels',
    'Bulgari',
    'Chopard',
    'Tiffany & Co.',
    'Boucheron',
    'Chaumet',
    'Mauboussin',
    'Mellerio',
    'Mikimoto',
    'Dinh Van',
    'Pomellato',
    'Buccellati',
    'Graff',
    'Harry Winston',
    'Piaget',
    'Messika',
    'Fred',
  ],
  watchBrands: [
    'Rolex',
    'Patek Philippe',
    'Audemars Piguet',
    'Cartier',
    'Omega',
    'Breitling',
    'Vacheron Constantin',
    'IWC',
    'Jaeger-LeCoultre',
    'Hublot',
    'Tudor',
    'Panerai',
  ],
} as const;

export const navigation = {
  primary: [
    { label: 'Accueil', href: '/' },
    {
      label: 'Nos rachats',
      href: '/rachat-de-diamants-saint-etienne',
      children: [
        { label: 'Rachat de diamants', href: '/rachat-de-diamants-saint-etienne' },
        { label: 'Rachat de bijoux', href: '/rachat-de-bijoux-saint-etienne' },
        { label: 'Bijoux signés', href: '/rachat-bijoux-signes-saint-etienne' },
        { label: 'Rachat d’or', href: '/rachat-or-saint-etienne' },
        { label: 'Montres de luxe', href: '/rachat-montres-luxe-saint-etienne' },
        { label: 'Perles & objets précieux', href: '/rachat-perles-saint-etienne' },
      ],
    },
    { label: 'Expertise', href: '/expertise-diamantaire-saint-etienne' },
    { label: 'Comment ça marche', href: '/comment-ca-marche' },
    { label: 'À propos', href: '/a-propos' },
    { label: 'Blog', href: '/blog' },
    { label: 'Contact', href: '/contact' },
  ],
  footer: [
    { label: 'Estimation gratuite', href: '/estimation-gratuite' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Mentions légales', href: '/mentions-legales' },
    { label: 'Politique de confidentialité', href: '/politique-confidentialite' },
    { label: 'Plan du site', href: '/sitemap.xml' },
  ],
} as const;
